In [1]:
from DataHandler import dgp_config as dcf
from DataHandler.equity_data import get_stock_ret, get_index_ret, get_period_end_dates, get_stock_ret_freqs

In [4]:
index_df = get_index_ret(freq="month", country="CN")
print("Index Return Data:", index_df.shape)
index_df.head()

Index Return Data: (185, 2)

        date       Ret
0 2010-01-29  0.018603
1 2010-02-26 -0.076799
2 2010-03-31 -0.097027
3 2010-04-30 -0.074749
4 2010-05-31  0.099714

In [5]:
period_end_df = get_stock_ret_freqs(freq="month", country="CN")
print("Period End Data:", index_df.shape)
period_end_df.head()

📂 Loaded from cache: ..\CACHE_DIR\CN_stock_ret_month.pq
Period End Data: (185, 2)

,Date,StockID,MarketCap,log_ret,Ret_5d,Ret_20d,Ret_60d,Ret_6-20d,Ret_6-60d,month_ret,next_month_ret,next_month_ret_0delay
0,1991-04-30,000001,1.157520e+06,-0.005024,-0.029762,-0.104625,-0.309984,0.078242,0.399142,-0.122253,-0.113460,-0.113460
1,1991-05-31,000001,1.016010e+06,-0.004943,-0.029734,-0.100157,-0.581402,0.072754,1.306052,-0.113460,-0.130922,-0.130922
2,1991-06-28,000001,9.007350e+05,-0.004989,-0.034716,-0.444304,-0.270437,0.728600,0.316647,-0.130922,-0.411587,-0.411587
3,1991-07-31,000001,7.828100e+05,-0.005065,-0.382166,-0.462583,-0.060502,0.135038,-0.350729,-0.411587,0.793331,0.793331
4,1991-08-31,000001,5.823657e+05,-0.003328,-0.086667,-0.060002,1.436659,-0.017729,-0.621066,0.793331,0.022304,0.022304